apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rsvp-ingress
  namespace: rsvp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: rsvp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rsvp
                port:
                  number: 5000

