apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp
  namespace: rsvp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rsvp
  template:
    metadata:
      labels:
        app: rsvp
    spec:
      containers:
        - name: rsvp
          image: teamcloudyuga/rsvpapp
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: rsvp-config
                  key: MONGODB_HOST
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: rsvp-config
                  key: MONGODB_PORT
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: rsvp-config
                  key: MONGODB_DATABASE
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_PASSWORD

