apiVersion: v1
kind: Service
metadata:
  name: rsvp
  namespace: rsvp
spec:
  type: NodePort
  selector:
    app: rsvp
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000
      protocol: TCP

